// flow-typed signature: c6e297339a990f89a20d388040608f82
// flow-typed version: <<STUB>>/react-final-form_v^3.1.2/flow_v0.66.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-final-form'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-final-form' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-final-form/dist/react-final-form.cjs' {
  declare module.exports: any;
}

declare module 'react-final-form/dist/react-final-form.es' {
  declare module.exports: any;
}

declare module 'react-final-form/dist/react-final-form.umd' {
  declare module.exports: any;
}

declare module 'react-final-form/dist/react-final-form.umd.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-final-form/dist/react-final-form.cjs.js' {
  declare module.exports: $Exports<'react-final-form/dist/react-final-form.cjs'>;
}
declare module 'react-final-form/dist/react-final-form.es.js' {
  declare module.exports: $Exports<'react-final-form/dist/react-final-form.es'>;
}
declare module 'react-final-form/dist/react-final-form.umd.js' {
  declare module.exports: $Exports<'react-final-form/dist/react-final-form.umd'>;
}
declare module 'react-final-form/dist/react-final-form.umd.min.js' {
  declare module.exports: $Exports<'react-final-form/dist/react-final-form.umd.min'>;
}
