/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface Stream {
  id?: string;
  kind?: string;
  name: string;
  profiles?: {
    width: number;
    name: string;
    height: number;
    bitrate: number;
    fps: number;
  }[];
  objectStoreId?: string;
  presets?: (
    | "P720p60fps16x9"
    | "P720p30fps16x9"
    | "P720p30fps4x3"
    | "P576p30fps16x9"
    | "P360p30fps16x9"
    | "P360p30fps4x3"
    | "P240p30fps16x9"
    | "P240p30fps4x3"
    | "P144p30fps16x9"
  )[];
  wowza?: {
    transcoderAppConfig: {
      [k: string]: any;
    };
    transcoderTemplateAppConfig: {
      [k: string]: any;
    };
    streamNameGroups: any[];
    sourceInfo: {
      width: number;
      height: number;
      fps: number;
    };
  };
  renditions?: {
    [k: string]: string;
  };
}

/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface Error {
  errors: [string, ...string[]];
  [k: string]: any;
}

/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface Objectstores {
  /**
   * type of object store used, such as 'aws'
   */
  type: string;
  /**
   * formatted as 'region/bucket'
   */
  path: string;
  /**
   * formatted as 'accesskeyid/accesskey'
   */
  credentials: string;
  id?: string;
  userId?: string;
}

/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface User {
  /**
   * user email address
   */
  email: string;
  password: string;
  salt?: string;
  admin?: boolean;
  kind?: string;
}
