// flow-typed signature: 075e0dc22283cf8c9416f2c2ef03790b
// flow-typed version: <<STUB>>/bn.js_v^4.11.8/flow_v0.66.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'bn.js'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'bn.js' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'bn.js/lib/bn' {
  declare module.exports: any;
}

declare module 'bn.js/util/genCombMulTo' {
  declare module.exports: any;
}

declare module 'bn.js/util/genCombMulTo10' {
  declare module.exports: any;
}

// Filename aliases
declare module 'bn.js/lib/bn.js' {
  declare module.exports: $Exports<'bn.js/lib/bn'>;
}
declare module 'bn.js/util/genCombMulTo.js' {
  declare module.exports: $Exports<'bn.js/util/genCombMulTo'>;
}
declare module 'bn.js/util/genCombMulTo10.js' {
  declare module.exports: $Exports<'bn.js/util/genCombMulTo10'>;
}
