import { Router } from 'express'
import uuid from 'uuid/v4'
import { generateStreamKey } from '../util'

const router = Router()

router.get('/', async (req, res) => {
  const output = await req.store.list('ingress/')
  res.status(200)
  res.json(output)
})

router.get('/:id', async (req, res) => {
  const { id } = req.params
  const data = await req.store.get(`ingress/${id}`)
  res.status(200)
  res.json(data)
})

router.post('/', async (req, res) => {
  const { body } = req

  if (body.id || body.key) {
    res.status(422)
    return res.json({
      errors: ['id and key are generated by the server'],
    })
  }

  const id = uuid()
  const key = await generateStreamKey()

  const data = {
    id: `ingress/${id}`,
    key,
    ...body,
  }

  const validate = req.validators.ingress

  console.log(validate)

  const valid = validate(data)
  if (!valid) {
    res.status(422)
    return res.json({
      errors: validate.errors.map(({ message }) => message),
    })
  }

  await req.store.create(data)

  res.status(201)
  res.json(data)
})

router.put('/:id', async (req, res) => {
  const data = req.body

  if (data.id !== `ingress/${req.params.id}`) {
    res.status(409)
    return res.json({ errors: ['id in URL and body must match'] })
  }

  const validate = req.validators.ingress

  const valid = validate(data)
  if (!valid) {
    res.status(422)
    return res.json({
      errors: validate.errors.map(({ message }) => message),
    })
  }

  await req.store.replace(data)
  res.status(200)
  res.json(data)
})

router.delete('/:id', async (req, res) => {
  await req.store.delete(`ingress/${req.params.id}`)
  res.sendStatus(204)
})

export default router
